org: ieeeutec
service: api-comentario

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20

  # Variables de entorno para la Lambda
  environment:
    TABLE_NAME: ${sls:stage}-t_comentarios
    BUCKET_NAME: ${sls:stage}-b-comentarios-ingesta # <-- NUEVA VARIABLE

  # Permisos IAM que Serverless gestionará
  iam:
    role:
      statements:
        # Permiso para escribir en DynamoDB
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TABLE_NAME}"
        # Permiso para escribir en el nuevo Bucket S3
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"

functions:
  crear:
    handler: comentario.lambda_handler
    events:
      - http:
          path: /comentario/crear
          method: post
          cors: true
          integration: lambda

# Recursos que Serverless creará (tablas, buckets, etc.)
resources:
  Resources:
    # Definición de la tabla DynamoDB (sin cambios)
    TablaComentarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # --- NUEVO BUCKET S3 ---
    # Definición del bucket S3 de ingesta
    BucketIngestaComentarios:
      Type: AWS::S3::Bucket
      Properties:
        # El nombre del bucket usará la variable de entorno
        BucketName: ${self:provider.environment.BUCKET_NAME}
